project_id = "fbffryjvvykhgoviektl"

[functions.analyze-store-data]
verify_jwt = false

[functions.analyze-retail-data]
verify_jwt = true

[functions.graph-query]
verify_jwt = true

[functions.advanced-ai-inference]
verify_jwt = true

[functions.schema-etl]
verify_jwt = true
