project_id = "bdrvowacecxnraaivlhr"

[functions.sync-api-data]
verify_jwt = false

[functions.schedule-runner]
verify_jwt = false

[functions.infer-entity-relations]
verify_jwt = false

[functions.ontology-inference-scheduler]
verify_jwt = false

[functions.ontology-ai-inference]
verify_jwt = true
